version: "2"
linters:
  enable:
    - gocritic
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(mc2lua)
        - default
run:
  timeout: 5m
