linters:
  enable:
    - gci
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple
    - gosec
    - gocritic

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(mc2lua)
      - default

run:
  timeout: 5m
