package pipeline

import (
	"fmt"
	"math"
	"strings"

	"mc2lua/internal/model"
)

const (
	coordPrecision      = 100.0
	partsPlaceholder    = "-- Total parts: XXX"
	importedFolderName  = "Imported"
	progressLogInterval = 500
)

type LuaGenerator struct {
	fs fsApi
}

func NewLuaGenerator(fs fsApi) *LuaGenerator {
	return &LuaGenerator{fs: fs}
}

func (svc *LuaGenerator) Run(parts []model.Part, scale float64, outputPath string) error {
	var sb strings.Builder
	svc.writeHeader(&sb, scale)

	totalParts := 0
	currentGroupID := 0

	for _, p := range parts {
		if p.GroupID != currentGroupID {
			if p.GroupID > 0 {
				svc.writeBeginGroup(&sb, p.Group)
			}
			currentGroupID = p.GroupID
		}
		parent := "folder"
		if p.GroupID > 0 {
			parent = "_group"
		}
		svc.writeCreatePart(&sb, p, parent)
		totalParts++
	}

	sb.WriteString("print(string.format(\"Building... %d/%d (100%%)\", _total, _total))\n")

	result := sb.String()
	result = strings.Replace(result, partsPlaceholder,
		fmt.Sprintf("-- Total parts: %d\nlocal _total = %d", totalParts, totalParts), 1)

	w, err := svc.fs.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}
	if _, err := w.Write([]byte(result)); err != nil {
		_ = w.Close()
		return fmt.Errorf("failed to write output file: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}

func (svc *LuaGenerator) writeHeader(sb *strings.Builder, scale float64) {
	sb.WriteString("-- Auto-generated by mc2lua\n")
	fmt.Fprintf(sb, "-- Scale: %g\n", scale)
	sb.WriteString(partsPlaceholder + "\n")
	sb.WriteString("local _counter = 0\n")
	sb.WriteString("local _group\n\n")
	fmt.Fprintf(sb, "local _tile = %g\n\n", scale)
	sb.WriteString("local faceEnum = {\n")
	sb.WriteString("    top = Enum.NormalId.Top,\n")
	sb.WriteString("    bottom = Enum.NormalId.Bottom,\n")
	sb.WriteString("    front = Enum.NormalId.Front,\n")
	sb.WriteString("    back = Enum.NormalId.Back,\n")
	sb.WriteString("    left = Enum.NormalId.Left,\n")
	sb.WriteString("    right = Enum.NormalId.Right,\n")
	sb.WriteString("}\n\n")
	sb.WriteString("local folder = Instance.new(\"Folder\")\n")
	fmt.Fprintf(sb, "folder.Name = %q\n", importedFolderName)
	sb.WriteString("folder.Parent = workspace\n\n")
	sb.WriteString("local function createPart(size, pos, r, g, b, material, name, blockId, properties, transparency, faces, parent)\n")
	sb.WriteString("    local p = Instance.new(\"Part\")\n")
	sb.WriteString("    p.Size = size\n")
	sb.WriteString("    p.Position = pos\n")
	sb.WriteString("    p.Color = Color3.fromRGB(r, g, b)\n")
	sb.WriteString("    p.Anchored = true\n")
	sb.WriteString("    p.Material = Enum.Material[material]\n")
	sb.WriteString("    p.Name = name\n")
	sb.WriteString("    p:SetAttribute(\"original_block_id\", blockId)\n")
	sb.WriteString("    p:SetAttribute(\"original_properties\", properties)\n")
	sb.WriteString("    if transparency then\n")
	sb.WriteString("        p.Transparency = transparency\n")
	sb.WriteString("    end\n")
	sb.WriteString("    if faces then\n")
	sb.WriteString("        for _, f in ipairs(faces) do\n")
	sb.WriteString("            local t = Instance.new(\"Texture\")\n")
	sb.WriteString("            t.Face = faceEnum[f.face]\n")
	sb.WriteString("            t.Texture = f.texture\n")
	sb.WriteString("            t.StudsPerTileU = f.studs_per_tile or _tile\n")
	sb.WriteString("            t.StudsPerTileV = f.studs_per_tile or _tile\n")
	sb.WriteString("            if f.color then\n")
	sb.WriteString("                t.Color3 = f.color\n")
	sb.WriteString("            end\n")
	sb.WriteString("            if f.transparency then\n")
	sb.WriteString("                t.Transparency = f.transparency\n")
	sb.WriteString("            end\n")
	sb.WriteString("            t.Parent = p\n")
	sb.WriteString("        end\n")
	sb.WriteString("    end\n")
	sb.WriteString("    p.Parent = parent or folder\n")
	sb.WriteString("\n")
	sb.WriteString("    _counter = _counter + 1\n")
	fmt.Fprintf(sb, "    if _counter %% %d == 0 then\n", progressLogInterval)
	sb.WriteString("        print(string.format(\"Building... %d/%d (%d%%)\", _counter, _total, _counter / _total * 100))\n")
	sb.WriteString("        task.wait()\n")
	sb.WriteString("    end\n")
	sb.WriteString("end\n\n")
}

func (svc *LuaGenerator) writeCreatePart(sb *strings.Builder, p model.Part, parent string) {
	fmt.Fprintf(sb,
		"createPart(Vector3.new(%g, %g, %g), Vector3.new(%g, %g, %g), %d, %d, %d, %q, %q, %q, %q, %s, %s, %s)\n",
		svc.roundCoord(p.Size[0]), svc.roundCoord(p.Size[1]), svc.roundCoord(p.Size[2]),
		svc.roundCoord(p.Position[0]), svc.roundCoord(p.Position[1]), svc.roundCoord(p.Position[2]),
		p.Color[0], p.Color[1], p.Color[2], p.Material, p.Name, p.BlockID, p.PropsKey,
		svc.luaTransparency(p), svc.luaFaces(p), parent,
	)
}

func (svc *LuaGenerator) luaTransparency(p model.Part) string {
	if p.Transparency == nil {
		return "nil"
	}
	return fmt.Sprintf("%g", *p.Transparency)
}

func (svc *LuaGenerator) luaFaces(p model.Part) string {
	faces := []struct {
		name string
		surf *model.Surface
	}{
		{model.FaceTop, p.Top},
		{model.FaceBottom, p.Bottom},
		{model.FaceFront, p.Front},
		{model.FaceBack, p.Back},
		{model.FaceLeft, p.Left},
		{model.FaceRight, p.Right},
	}

	var entries []string
	for _, f := range faces {
		if f.surf == nil || f.surf.Texture == "" {
			continue
		}
		parts := []string{
			fmt.Sprintf("face=%q", f.name),
			fmt.Sprintf("texture=%q", f.surf.Texture),
		}
		if f.surf.Color != nil {
			parts = append(parts, fmt.Sprintf("color=Color3.fromRGB(%d, %d, %d)", f.surf.Color[0], f.surf.Color[1], f.surf.Color[2]))
		}
		if f.surf.Transparency != nil {
			parts = append(parts, fmt.Sprintf("transparency=%g", *f.surf.Transparency))
		}
		if f.surf.StudsPerTile != nil {
			parts = append(parts, fmt.Sprintf("studs_per_tile=%g", *f.surf.StudsPerTile))
		}
		entries = append(entries, "{"+strings.Join(parts, ", ")+"}")
	}

	if len(entries) == 0 {
		return "nil"
	}
	return "{" + strings.Join(entries, ", ") + "}"
}

func (svc *LuaGenerator) roundCoord(v float64) float64 {
	return math.Round(v*coordPrecision) / coordPrecision
}

func (svc *LuaGenerator) writeBeginGroup(sb *strings.Builder, groupName string) {
	sb.WriteString("_group = Instance.new(\"Folder\")\n")
	fmt.Fprintf(sb, "_group.Name = %q\n_group.Parent = folder\n", groupName)
}
