package pipeline

import (
	"fmt"
	"math"
	"os"
	"strings"

	"mc2lua/internal/minecraft"
	"mc2lua/internal/stateful"
	"mc2lua/internal/model"
)

const (
	coordPrecision       = 100.0
	outputFilePermission = 0644
	partsPlaceholder     = "-- Total parts: XXX"
	importedFolderName   = "Imported"
	elementNameFormat    = "elem %d"
)

type generatorPropsKeyBuilder interface {
	Run(props map[string]string) string
}
type LuaGenerator struct {
	propsKeyBuilder generatorPropsKeyBuilder
}

func NewLuaGenerator(pkb generatorPropsKeyBuilder) *LuaGenerator {
	return &LuaGenerator{propsKeyBuilder: pkb}
}

func (svc *LuaGenerator) Run(blocks []model.RawBlock, blockCuboids, microCuboids []model.Cuboid, styleIndex stateful.StyleIndex, scale float64, outputPath string) (int, error) {
	var sb strings.Builder
	svc.writeHeader(&sb, scale)

	totalParts := 0

	for _, cuboids := range [][]model.Cuboid{blockCuboids, microCuboids} {
		for _, c := range cuboids {
			style, ok := styleIndex.Get(c.ID, c.PropsKey)
			if !ok {
				continue
			}
			if style.GridAlignment == model.GridNotAligned {
				continue
			}
			if err := svc.writeSimplePart(&sb, c, style, scale); err != nil {
				return 0, fmt.Errorf("failed to write simple part for block ID %s with properties %s: %w", c.ID, c.PropsKey, err)
			}
			totalParts++
		}
	}

	for _, r := range blocks {
		propsKey := svc.propsKeyBuilder.Run(r.Props)
		style, ok := styleIndex.Get(r.ID, propsKey)
		if ok && style.GridAlignment == model.GridNotAligned {
			totalParts += svc.writeComplexParts(&sb, r, style, scale)
		}
	}

	sb.WriteString("print(string.format(\"Building... %d/%d (100%%)\", _total, _total))\n")

	result := sb.String()
	result = strings.Replace(result, partsPlaceholder,
		fmt.Sprintf("-- Total parts: %d\nlocal _total = %d", totalParts, totalParts), 1)

	if err := os.WriteFile(outputPath, []byte(result), outputFilePermission); err != nil {
		return 0, fmt.Errorf("failed to write output file: %w", err)
	}

	return totalParts, nil
}

func (svc *LuaGenerator) writeHeader(sb *strings.Builder, scale float64) {
	sb.WriteString("-- Auto-generated by mc2lua\n")
	sb.WriteString(fmt.Sprintf("-- Scale: %g\n", scale))
	sb.WriteString(partsPlaceholder + "\n")
	sb.WriteString("local _counter = 0\n")
	sb.WriteString("local _group\n\n")
	sb.WriteString("local folder = Instance.new(\"Folder\")\n")
	sb.WriteString(fmt.Sprintf("folder.Name = %q\n", importedFolderName))
	sb.WriteString("folder.Parent = workspace\n\n")
	sb.WriteString("local function createPart(size, pos, r, g, b, material, name, blockId, properties, parent)\n")
	sb.WriteString("    local p = Instance.new(\"Part\")\n")
	sb.WriteString("    p.Size = size\n")
	sb.WriteString("    p.Position = pos\n")
	sb.WriteString("    p.Color = Color3.fromRGB(r, g, b)\n")
	sb.WriteString("    p.Anchored = true\n")
	sb.WriteString("    p.Material = Enum.Material[material]\n")
	sb.WriteString("    p.Name = name\n")
	sb.WriteString("    p:SetAttribute(\"original_block_id\", blockId)\n")
	sb.WriteString("    p:SetAttribute(\"original_properties\", properties)\n")
	sb.WriteString("    p.Parent = parent or folder\n")
	sb.WriteString("\n")
	sb.WriteString("    _counter = _counter + 1\n")
	sb.WriteString("    if _counter % 500 == 0 then\n")
	sb.WriteString("        print(string.format(\"Building... %d/%d (%d%%)\", _counter, _total, _counter / _total * 100))\n")
	sb.WriteString("        task.wait()\n")
	sb.WriteString("    end\n")
	sb.WriteString("end\n\n")
}

func (svc *LuaGenerator) writeCreatePart(sb *strings.Builder, w, h, d float64, px, py, pz float64, color model.Color, material, name, blockID, properties string, parent string) {
	sb.WriteString(fmt.Sprintf(
		"createPart(Vector3.new(%g, %g, %g), Vector3.new(%g, %g, %g), %d, %d, %d, %q, %q, %q, %q, %s)\n",
		svc.roundCoord(w), svc.roundCoord(h), svc.roundCoord(d), svc.roundCoord(px), svc.roundCoord(py), svc.roundCoord(pz),
		color[0], color[1], color[2], material, name, blockID, properties, parent,
	))
}

func (svc *LuaGenerator) roundCoord(v float64) float64 {
	return math.Round(v*coordPrecision) / coordPrecision
}

func (svc *LuaGenerator) writeSimplePart(sb *strings.Builder, cuboid model.Cuboid, style model.StyledBlock, scale float64) error {
	if len(style.Elements) == 0 {
		return fmt.Errorf("no elements found for block ID %s with properties %s", cuboid.ID, cuboid.PropsKey)
	}

	elem := style.Elements[0]

	gs := 1.0
	if style.GridAlignment == model.GridSubBlock {
		gs = float64(model.SubGridSize)
	}

	x := (float64(cuboid.X) - (gs-1)/2) * scale / gs
	y := (float64(cuboid.Y) - (gs-1)/2) * scale / gs
	z := (float64(cuboid.Z) - (gs-1)/2) * scale / gs
	width := float64(cuboid.Width) * scale / gs
	height := float64(cuboid.Height) * scale / gs
	depth := float64(cuboid.Depth) * scale / gs
	name := svc.makePartName(cuboid.ID)

	svc.writeCreatePart(sb, width, height, depth, x, y, z, elem.Color, elem.Material, name, cuboid.ID, cuboid.PropsKey, "folder")
	return nil
}

func (svc *LuaGenerator) writeComplexParts(sb *strings.Builder, block model.RawBlock, style model.StyledBlock, scale float64) int {
	if len(style.Elements) == 0 {
		return 0
	}
	count := 0

	xBase := float64(block.X)*scale - scale/2.0
	yBase := float64(block.Y)*scale - scale/2.0
	zBase := float64(block.Z)*scale - scale/2.0

	parent := "folder"
	if len(style.Elements) > 1 {
		firstPos := svc.elementKey(style.Elements[0], xBase, yBase, zBase, scale)
		distinct := false
		for _, elem := range style.Elements[1:] {
			if svc.elementKey(elem, xBase, yBase, zBase, scale) != firstPos {
				distinct = true
				break
			}
		}
		if distinct {
			svc.writeBeginGroup(sb, svc.makePartName(block.ID))
			parent = "_group"
		}
	}

	for idx, elem := range style.Elements {
		sizeX := (elem.To[0] - elem.From[0]) / model.FullBlockSize * scale
		sizeY := (elem.To[1] - elem.From[1]) / model.FullBlockSize * scale
		sizeZ := (elem.To[2] - elem.From[2]) / model.FullBlockSize * scale

		cx := (elem.From[0] + elem.To[0]) / 2.0 / model.FullBlockSize * scale
		cy := (elem.From[1] + elem.To[1]) / 2.0 / model.FullBlockSize * scale
		cz := (elem.From[2] + elem.To[2]) / 2.0 / model.FullBlockSize * scale

		px := xBase + cx
		py := yBase + cy
		pz := zBase + cz

		partName := svc.makePartName(block.ID)
		if parent == "_group" {
			partName = fmt.Sprintf(elementNameFormat, idx+1)
		}

		svc.writeCreatePart(sb, sizeX, sizeY, sizeZ, px, py, pz, elem.Color, elem.Material, partName, block.ID, style.PropsKey, parent)
		count++
	}
	return count
}

func (svc *LuaGenerator) elementKey(elem model.StyledElement, xBase, yBase, zBase, scale float64) string {
	cx := xBase + (elem.From[0]+elem.To[0])/2.0/model.FullBlockSize*scale
	cy := yBase + (elem.From[1]+elem.To[1])/2.0/model.FullBlockSize*scale
	cz := zBase + (elem.From[2]+elem.To[2])/2.0/model.FullBlockSize*scale
	return fmt.Sprintf("%.4f,%.4f,%.4f", cx, cy, cz)
}

func (svc *LuaGenerator) writeBeginGroup(sb *strings.Builder, groupName string) {
	sb.WriteString("_group = Instance.new(\"Folder\")\n")
	sb.WriteString(fmt.Sprintf("_group.Name = %q\n_group.Parent = folder\n", groupName))
}

func (svc *LuaGenerator) makePartName(blockID string) string {
	return strings.TrimPrefix(blockID, minecraft.MinecraftNamespacePrefix)
}
