package pipeline

import (
	"fmt"
	"math"
	"strings"

	"mc2lua/internal/model"
)

const (
	coordPrecision     = 100.0
	partsPlaceholder   = "-- Total parts: XXX"
	importedFolderName = "Imported"
)

type LuaGenerator struct {
	fs fsApi
}

func NewLuaGenerator(fs fsApi) *LuaGenerator {
	return &LuaGenerator{fs: fs}
}

func (svc *LuaGenerator) Run(parts []model.Part, scale float64, outputPath string) error {
	var sb strings.Builder
	svc.writeHeader(&sb, scale)

	totalParts := 0
	currentGroupID := 0

	for _, p := range parts {
		if p.GroupID != currentGroupID {
			if p.GroupID > 0 {
				svc.writeBeginGroup(&sb, p.Group)
			}
			currentGroupID = p.GroupID
		}
		parent := "folder"
		if p.GroupID > 0 {
			parent = "_group"
		}
		svc.writeCreatePart(&sb, p, parent)
		totalParts++
	}

	sb.WriteString("print(string.format(\"Building... %d/%d (100%%)\", _total, _total))\n")

	result := sb.String()
	result = strings.Replace(result, partsPlaceholder,
		fmt.Sprintf("-- Total parts: %d\nlocal _total = %d", totalParts, totalParts), 1)

	w, err := svc.fs.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}
	if _, err := w.Write([]byte(result)); err != nil {
		_ = w.Close()
		return fmt.Errorf("failed to write output file: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	return nil
}

func (svc *LuaGenerator) writeHeader(sb *strings.Builder, scale float64) {
	sb.WriteString("-- Auto-generated by mc2lua\n")
	fmt.Fprintf(sb, "-- Scale: %g\n", scale)
	sb.WriteString(partsPlaceholder + "\n")
	sb.WriteString("local _counter = 0\n")
	sb.WriteString("local _group\n\n")
	sb.WriteString("local folder = Instance.new(\"Folder\")\n")
	fmt.Fprintf(sb, "folder.Name = %q\n", importedFolderName)
	sb.WriteString("folder.Parent = workspace\n\n")
	sb.WriteString("local function createPart(size, pos, r, g, b, material, name, blockId, properties, parent)\n")
	sb.WriteString("    local p = Instance.new(\"Part\")\n")
	sb.WriteString("    p.Size = size\n")
	sb.WriteString("    p.Position = pos\n")
	sb.WriteString("    p.Color = Color3.fromRGB(r, g, b)\n")
	sb.WriteString("    p.Anchored = true\n")
	sb.WriteString("    p.Material = Enum.Material[material]\n")
	sb.WriteString("    p.Name = name\n")
	sb.WriteString("    p:SetAttribute(\"original_block_id\", blockId)\n")
	sb.WriteString("    p:SetAttribute(\"original_properties\", properties)\n")
	sb.WriteString("    p.Parent = parent or folder\n")
	sb.WriteString("\n")
	sb.WriteString("    _counter = _counter + 1\n")
	sb.WriteString("    if _counter % 500 == 0 then\n")
	sb.WriteString("        print(string.format(\"Building... %d/%d (%d%%)\", _counter, _total, _counter / _total * 100))\n")
	sb.WriteString("        task.wait()\n")
	sb.WriteString("    end\n")
	sb.WriteString("end\n\n")
}

func (svc *LuaGenerator) writeCreatePart(sb *strings.Builder, p model.Part, parent string) {
	fmt.Fprintf(sb,
		"createPart(Vector3.new(%g, %g, %g), Vector3.new(%g, %g, %g), %d, %d, %d, %q, %q, %q, %q, %s)\n",
		svc.roundCoord(p.Size[0]), svc.roundCoord(p.Size[1]), svc.roundCoord(p.Size[2]),
		svc.roundCoord(p.Position[0]), svc.roundCoord(p.Position[1]), svc.roundCoord(p.Position[2]),
		p.Color[0], p.Color[1], p.Color[2], p.Material, p.Name, p.BlockID, p.PropsKey, parent,
	)
}

func (svc *LuaGenerator) roundCoord(v float64) float64 {
	return math.Round(v*coordPrecision) / coordPrecision
}

func (svc *LuaGenerator) writeBeginGroup(sb *strings.Builder, groupName string) {
	sb.WriteString("_group = Instance.new(\"Folder\")\n")
	fmt.Fprintf(sb, "_group.Name = %q\n_group.Parent = folder\n", groupName)
}
