package pipeline

import (
	"errors"
	"fmt"
	"strings"
	"testing"

	"mc2lua/internal/model"
	"mc2lua/internal/runtime"

	"github.com/stretchr/testify/require"
)

func testLuaGenerator(t *testing.T) (*LuaGenerator, *runtime.FSMock) {
	t.Helper()
	mockFS := runtime.NewFSMock()
	return NewLuaGenerator(mockFS), mockFS
}

func makePart(name, group string, groupID int, blockID, propsKey string, size, pos model.Vector3, color model.Color, material string) model.Part {
	return model.Part{
		Name:     name,
		Group:    group,
		GroupID:  groupID,
		BlockID:  blockID,
		PropsKey: propsKey,
		Size:     size,
		Position: pos,
		Color:    color,
		Material: material,
	}
}

func TestLuaGenerator_New(t *testing.T) {
	t.Parallel()

	lg := NewLuaGenerator(runtime.NewFSMock())
	require.NotNil(t, lg)
}

func TestWriteHeader(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	svc.writeHeader(&sb, 4)
	got := sb.String()

	checks := []string{
		"-- Auto-generated by mc2lua",
		"-- Scale: 4",
		"-- Total parts: XXX",
		"local _counter = 0",
		"local _group",
		"local _tile = 4",
		"top = Enum.NormalId.Top",
		"bottom = Enum.NormalId.Bottom",
		"front = Enum.NormalId.Front",
		"back = Enum.NormalId.Back",
		"left = Enum.NormalId.Left",
		"right = Enum.NormalId.Right",
		"local folder = Instance.new(\"Folder\")",
		"folder.Name = \"Imported\"",
		"folder.Parent = workspace",
		"local function createPart(size, pos, r, g, b, material, name, blockId, properties, transparency, faces, parent)",
		"p:SetAttribute(\"original_block_id\", blockId)",
	}

	for _, c := range checks {
		require.Contains(t, got, c)
	}
}

func TestWriteCreatePart(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	svc.writeCreatePart(&sb, makePart(
		"stone", "", 0, "minecraft:stone", "",
		model.Vector3{2, 3, 4}, model.Vector3{1.5, 2.5, 3.5},
		model.Color{255, 128, 64}, "Wood",
	), "folder")
	got := sb.String()

	require.Contains(t, got, "createPart(")
	require.Contains(t, got, "Vector3.new(2, 3, 4)")
	require.Contains(t, got, "Vector3.new(1.5, 2.5, 3.5)")
	require.Contains(t, got, "255, 128, 64")
	require.Contains(t, got, `"Wood"`)
	require.Contains(t, got, `"stone"`)
	require.Contains(t, got, `"minecraft:stone"`)
	require.Contains(t, got, ", folder)")
}

func TestWriteCreatePart_RoundsCoordinates(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	svc.writeCreatePart(&sb, makePart(
		"bush", "", 0, "minecraft:bush", "",
		model.Vector3{292.00000000000006, 12, 8}, model.Vector3{3.5999999999999996, 4, 0},
		model.Color{139, 140, 139}, "SmoothPlastic",
	), "folder")
	got := sb.String()

	require.Contains(t, got, "Vector3.new(292, 12, 8)")
	require.Contains(t, got, "Vector3.new(3.6, 4, 0)")
	require.NotContains(t, got, "3.5999999999999996")
}

func TestWriteBeginGroup(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	svc.writeBeginGroup(&sb, "oak_stairs")
	got := sb.String()

	require.Contains(t, got, "_group = Instance.new(\"Folder\")")
	require.Contains(t, got, "_group.Name = \"oak_stairs\"")
	require.Contains(t, got, "_group.Parent = folder")
}

func TestWriteCreatePart_Transparency(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	part := makePart(
		"glass", "", 0, "minecraft:glass", "",
		model.Vector3{4, 4, 4}, model.Vector3{0, 0, 0},
		model.Color{255, 255, 255}, "SmoothPlastic",
	)
	part.Transparency = floatPtr(0.5)
	svc.writeCreatePart(&sb, part, "folder")
	got := sb.String()

	require.Contains(t, got, ", 0.5, nil, folder)")
}

func TestWriteCreatePart_Faces(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	part := makePart(
		"oak", "", 0, "minecraft:oak", "",
		model.Vector3{4, 4, 4}, model.Vector3{0, 0, 0},
		model.Color{131, 84, 50}, "SmoothPlastic",
	)
	red := model.Color{255, 0, 0}
	part.Top = surfPtr("rbxassetid://top", &red, floatPtr(0.2))
	part.Bottom = surfPtr("rbxassetid://bottom", nil, nil)
	svc.writeCreatePart(&sb, part, "folder")
	got := sb.String()

	require.Contains(t, got, `{face="top", texture="rbxassetid://top", color=Color3.fromRGB(255, 0, 0), transparency=0.2}`)
	require.Contains(t, got, `{face="bottom", texture="rbxassetid://bottom"}`)
	require.NotContains(t, got, `face="front"`)
}

func TestWriteCreatePart_SkipsTexturelessFaces(t *testing.T) {
	t.Parallel()

	svc, _ := testLuaGenerator(t)
	var sb strings.Builder
	part := makePart(
		"oak", "", 0, "minecraft:oak", "",
		model.Vector3{4, 4, 4}, model.Vector3{0, 0, 0},
		model.Color{131, 84, 50}, "Wood",
	)
	red := model.Color{255, 0, 0}
	part.Top = surfPtr("", &red, nil)
	part.Front = surfPtr("", nil, floatPtr(0.3))
	svc.writeCreatePart(&sb, part, "folder")
	got := sb.String()

	require.Contains(t, got, ", nil, nil, folder)")
	require.NotContains(t, got, "face=")
}

func TestRun(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		parts      []model.Part
		scale      float64
		wantErrMsg string
		wantCheck  func(t *testing.T, data string)
	}{
		{
			name:  "empty input",
			parts: nil,
			scale: 4,
			wantCheck: func(t *testing.T, data string) {
				require.Contains(t, data, "-- Auto-generated by mc2lua")
				require.Contains(t, data, "-- Total parts: 0\nlocal _total = 0")
			},
		},
		{
			name: "single full block",
			parts: []model.Part{
				makePart("stone", "", 0, "minecraft:stone", "", model.Vector3{4, 4, 4}, model.Vector3{0, 0, 0}, model.Color{128, 128, 128}, "Slate"),
			},
			scale: 4,
		},
		{
			name: "single micro block",
			parts: []model.Part{
				makePart("stone_slab", "", 0, "minecraft:stone_slab", "", model.Vector3{4, 2, 4}, model.Vector3{0, -1, 0}, model.Color{128, 128, 128}, "Stone"),
			},
			scale: 4,
			wantCheck: func(t *testing.T, data string) {
				require.Contains(t, data, "Vector3.new(4, 2, 4)")
				require.Contains(t, data, "Vector3.new(0, -1, 0)")
			},
		},
		{
			name: "grouped parts create group",
			parts: []model.Part{
				makePart("elem 1", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 4}, model.Vector3{0, 0, 2}, model.Color{131, 84, 50}, "Wood"),
				makePart("elem 2", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 2}, model.Vector3{0, 2, 0}, model.Color{131, 84, 50}, "Wood"),
			},
			scale: 4,
			wantCheck: func(t *testing.T, data string) {
				require.Contains(t, data, "Instance.new(\"Folder\")")
				require.Contains(t, data, "oak_stairs")
				require.Contains(t, data, ", _group)")
			},
		},
		{
			name: "groups with same name stay separate",
			parts: []model.Part{
				makePart("elem 1", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 4}, model.Vector3{0, 0, 2}, model.Color{131, 84, 50}, "Wood"),
				makePart("elem 2", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 2}, model.Vector3{0, 2, 0}, model.Color{131, 84, 50}, "Wood"),
				makePart("elem 1", "oak_stairs", 2, "minecraft:oak_stairs", "facing=south,half=bottom", model.Vector3{4, 2, 4}, model.Vector3{12, 0, 2}, model.Color{131, 84, 50}, "Wood"),
				makePart("elem 2", "oak_stairs", 2, "minecraft:oak_stairs", "facing=south,half=bottom", model.Vector3{4, 2, 2}, model.Vector3{12, 2, 0}, model.Color{131, 84, 50}, "Wood"),
			},
			scale: 4,
			wantCheck: func(t *testing.T, data string) {
				require.Equal(t, 2, strings.Count(data, "_group = Instance.new(\"Folder\")"))
				require.Equal(t, 2, strings.Count(data, "_group.Name = \"oak_stairs\""))
			},
		},
		{
			name: "folder and group parts",
			parts: []model.Part{
				makePart("stone", "", 0, "minecraft:stone", "", model.Vector3{4, 4, 4}, model.Vector3{0, 0, 0}, model.Color{128, 128, 128}, "Slate"),
				makePart("elem 1", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 4}, model.Vector3{4, 0, 2}, model.Color{131, 84, 50}, "Wood"),
				makePart("elem 2", "oak_stairs", 1, "minecraft:oak_stairs", "facing=north,half=bottom", model.Vector3{4, 2, 2}, model.Vector3{4, 2, 0}, model.Color{131, 84, 50}, "Wood"),
			},
			scale: 4,
			wantCheck: func(t *testing.T, data string) {
				require.Contains(t, data, ", folder)")
				require.Contains(t, data, ", _group)")
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			svc, mockFS := testLuaGenerator(t)
			outPath := "out.lua"

			err := svc.Run(tt.parts, tt.scale, outPath)
			if tt.wantErrMsg != "" {
				require.Error(t, err)
				require.Contains(t, err.Error(), tt.wantErrMsg)
				return
			}
			require.NoError(t, err)

			data, err := mockFS.ReadFile(outPath)
			require.NoError(t, err)

			require.Contains(t, string(data), fmt.Sprintf("-- Total parts: %d\nlocal _total = %d", len(tt.parts), len(tt.parts)))

			if tt.wantCheck != nil {
				tt.wantCheck(t, string(data))
			}
		})
	}
}

func TestRun_WriteError(t *testing.T) {
	t.Parallel()

	svc, mockFS := testLuaGenerator(t)
	outPath := "out.lua"
	mockFS.CreateErrors[outPath] = errors.New("create fail")
	err := svc.Run(nil, 4, outPath)
	require.Error(t, err)
	require.Contains(t, err.Error(), "failed to write output file")
}
