mappings:
  planks: Wood
  log: Wood
  wood: Wood
  fence: Wood
  door: Wood
  trapdoor: Wood
  button: Wood
  sign: Wood
  ladder: Wood
  bookshelf: Wood
  glass: Glass
  wool: Fabric
  carpet: Fabric
  banner: Fabric
  bed: Fabric
  stone: Slate
  brick: Slate
  deepslate: Slate
  tuff: Slate
  prismarine: Slate
  purpur: Slate
  end_stone: Slate
  cobblestone: Cobblestone
  cobbled: Cobblestone
  obsidian: Cobblestone
  netherrack: Cobblestone
  sand: Sand
  sandstone: Sand
  soul_sand: Sand
  soul_soil: Sand
  gravel: Pebble
  grass: Grass
  moss: Grass
  leaves: Grass
  foliage: Grass
  ice: Ice
  snow: Snow
  iron: Metal
  gold: Metal
  diamond: Metal
  anvil: Metal
  lantern: Neon
  glowstone: Neon
  froglight: Neon

suffixes:
  - _pressure_plate
  - _wall_sign
  - _fence_gate
  - _trapdoor
  - _stairs
  - _slab
  - _button
  - _fence
  - _bars
  - _door
  - _pane
  - _wall
  - _sign

overrides:
  minecraft:chain: Metal
  minecraft:iron_door: Metal
  minecraft:brewing_stand: Metal
  minecraft:azalea_leaves: Grass
  minecraft:flowering_azalea_leaves: Grass
  minecraft:mangrove_leaves: Grass
  minecraft:oak_leaves: Grass
  minecraft:moss_block: Grass
  minecraft:clay: SmoothPlastic
  minecraft:pumpkin: SmoothPlastic
  minecraft:end_rod: SmoothPlastic
  minecraft:candle: SmoothPlastic
  minecraft:coal_ore: SmoothPlastic
  minecraft:copper_ore: SmoothPlastic
  minecraft:bookshelf: Wood
  minecraft:barrel: Wood
  minecraft:composter: Wood
  minecraft:lectern: Wood
  minecraft:chiseled_bookshelf: Wood
  minecraft:lantern: Neon
