parts:
  minecraft:water:
    color: [38, 94, 173]

  minecraft:bubble_column:
    color: [38, 94, 173]

  minecraft:lava:
    color: [200, 82, 18]

  minecraft:grass_block:
    color: [44, 101, 29]
    all:
      texture: rbxassetid://321821235

  minecraft:glass:
    color: [191, 191, 191]
    transparency: 0.5
    all:
      texture: rbxassetid://232395521
