parts:
  minecraft:water:
    color: [38, 94, 173]

  minecraft:bubble_column:
    color: [38, 94, 173]

  minecraft:lava:
    color: [200, 82, 18]

  minecraft:grass_block:
    color: [44, 101, 29]
    all:
      texture: rbxassetid://321821235

  minecraft:oak_log:
    top:
      texture: rbxassetid://232395521
      color: [191, 134, 60]
    bottom:
      texture: rbxassetid://232395521
      color: [191, 134, 60]
    faces:
      texture: rbxassetid://232395521
      color: [120, 82, 40]

  minecraft:crafting_table:
    top:
      texture: rbxassetid://232395521
      color: [150, 110, 70]
    bottom:
      texture: rbxassetid://186400921
      color: [120, 90, 55]
    front:
      texture: rbxassetid://232395521
      color: [130, 95, 60]
    walls:
      texture: rbxassetid://232395521
      color: [125, 92, 58]

  minecraft:barrel:
    transparency: 0.0
    top:
      texture: rbxassetid://232395521
      color: [110, 78, 48]
    bottom:
      texture: rbxassetid://232395521
      color: [110, 78, 48]
    front:
      texture: rbxassetid://232395521
      color: [105, 74, 45]
    back:
      texture: rbxassetid://232395521
      color: [105, 74, 45]
    sides:
      texture: rbxassetid://232395521
      color: [100, 70, 42]

  minecraft:glass:
    transparency: 0.5
    all:
      texture: rbxassetid://232395521
      color: [191, 191, 191]
